### ISSUE TITLE
Add Documentation - How to patch

### ISSUE THREAD

**Issue by othello777** [surrealegg/omori-linux-patch#1]
I would like to play omori on linux. How do I apply this patch?

**Comment by surrealegg** [comment]
Hey! sorry for long response I will add a documentation as soon as possible.

**Comment by othello777** [comment]
Awesome. even just any hint as to what patching program to use

**Comment by othello777** [comment]
@surrealegg any progress?

**Comment by surrealegg** [comment]
I'm really sorry for no progress at all I have been really busy IRL and I wasn't able to spend time on it

**Comment by othello777** [comment]
understandable. It just came up again that I would like to be able to run omori optimized on linux, and this repo looks promising but I have no clue how to use it

**Comment by surrealegg** [comment]
Yeah sorry about that. I just created a pull request. Here are the instructions https://github.com/surrealegg/omori-linux-patch/blob/add-documentation/README.md let me know if there's any issues
